-ifdef(unit_test).
-define(ServiceSpecsGitPath,"https://github.com/joq62/test_service_specs.git").
-else.
-define(ServiceSpecsGitPath,"https://github.com/joq62/service_specs.git").
-endif.
-define(ServiceSpecsFilesDir,"service_specs").
-define(ScheduleInterval,1*60*1000).
